states_table = [
    {'value': 'US', 'label': 'United States', 'order_start_date': None, 
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'AL', 'label': 'Alabama', 'order_start_date': '20200403',
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'AK', 'label': 'Alaska', 'order_start_date': '20200327',
     'order_relaxed_date': None, 'order_canceled_date': '20200424'},
    {'value': 'AS', 'label': 'American Samoa', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'AZ', 'label': 'Arizona', 'order_start_date': '20200330',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'AR', 'label': 'Arkansas', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'CA', 'label': 'California', 'order_start_date': '20200319',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'CO', 'label': 'Colorado', 'order_start_date': '20200325',
     'order_relaxed_date': '20200426', 'order_canceled_date': None},
    {'value': 'CT', 'label': 'Connecticut', 'order_start_date': '20200320',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'DE', 'label': 'Delaware', 'order_start_date': '20200330',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'DC', 'label': 'District of Columbia',
     'order_start_date': None, 'order_relaxed_date': None,
     'order_canceled_date': None},
    {'value': 'FL', 'label': 'Florida', 'order_start_date': '20200401',
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'GA', 'label': 'Georgia', 'order_start_date': '20200402', 
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'GU', 'label': 'Guam', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'HI', 'label': 'Hawaii', 'order_start_date': '20200323',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'ID', 'label': 'Idaho', 'order_start_date': '20200325',
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'IL', 'label': 'Illinois', 'order_start_date': '20200320',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'IN', 'label': 'Indiana', 'order_start_date': '20200323', 
     'order_relaxed_date': None, 'order_canceled_date': '20200501'},
    {'value': 'IA', 'label': 'Iowa', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'KS', 'label': 'Kansas', 'order_start_date': '20200328',
     'order_relaxed_date': None, 'order_canceled_date': '20200501'},
    {'value': 'KY', 'label': 'Kentucky', 'order_start_date': '20200322',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'LA', 'label': 'Louisiana', 'order_start_date': '20200322',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'ME', 'label': 'Maine', 'order_start_date': '20200331',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MD', 'label': 'Maryland', 'order_start_date': '20200330',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MA', 'label': 'Massachusetts',
     'order_start_date': '20200323', 'order_relaxed_date': None,
     'order_canceled_date': None},
    {'value': 'MI', 'label': 'Michigan', 'order_start_date': '20200323',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MN', 'label': 'Minnesota', 'order_start_date': '20200325',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MS', 'label': 'Mississippi', 'order_start_date': '20200401',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MO', 'label': 'Missouri', 'order_start_date': '20200403',
     'order_relaxed_date': None, 'order_canceled_date': '20200503'},
    {'value': 'MT', 'label': 'Montana', 'order_start_date': '20200326',
     'order_relaxed_date': None, 'order_canceled_date': '20200427'},
    {'value': 'NE', 'label': 'Nebraska', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'NV', 'label': 'Nevada', 'order_start_date': '20200331',
     'order_relaxed_date': None, 'order_canceled_date': '20200508'},
    {'value': 'NH', 'label': 'New Hampshire', 
     'order_start_date': '20200326', 'order_relaxed_date': None, 
     'order_canceled_date': None},
    {'value': 'NJ', 'label': 'New Jersey', 'order_start_date': '20200321', 
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'NM', 'label': 'New Mexico', 'order_start_date': '20200323', 
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'NY', 'label': 'New York', 'order_start_date': '20200320', 
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'NC', 'label': 'North Carolina', 
     'order_start_date': '20200327', 'order_relaxed_date': None,
     'order_canceled_date': '20200508'},
    {'value': 'ND', 'label': 'North Dakota', 'order_start_date': None, 
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'MP', 'label': 'Northern Mariana Islands', 
     'order_start_date': None, 'order_relaxed_date': None, 
     'order_canceled_date': None},
    {'value': 'OH', 'label': 'Ohio', 'order_start_date': '20200322', 
     'order_relaxed_date': None, 'order_canceled_date': '20200501'},
    {'value': 'OK', 'label': 'Oklahoma', 'order_start_date': '20200401',
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'OR', 'label': 'Oregon', 'order_start_date': '20200323',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'PA', 'label': 'Pennsylvania', 'order_start_date': '20200401',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'PR', 'label': 'Puerto Rico', 'order_start_date': '20200315',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'RI', 'label': 'Rhode Island', 'order_start_date': '20200330',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'SC', 'label': 'South Carolina', 
     'order_start_date': '20200406', 'order_relaxed_date': None, 
     'order_canceled_date': '20200504'},
    {'value': 'SD', 'label': 'South Dakota', 'order_start_date': '20200323',
     'order_relaxed_date': None, 'order_canceled_date': '20200428'},
    {'value': 'TN', 'label': 'Tennessee', 'order_start_date': '20200330', 
     'order_relaxed_date': None, 'order_canceled_date': '20200429'},
    {'value': 'TX', 'label': 'Texas', 'order_start_date': '20200331',
     'order_relaxed_date': None, 'order_canceled_date': '20200430'},
    {'value': 'UT', 'label': 'Utah', 'order_start_date': '20200327', 
     'order_relaxed_date': None, 'order_canceled_date': '20200501'},
    {'value': 'VT', 'label': 'Vermont', 'order_start_date': '20200324',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'VI', 'label': 'Virgin Islands', 'order_start_date': None,
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'VA', 'label': 'Virginia', 'order_start_date': '20200330', 
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'WA', 'label': 'Washington', 'order_start_date': '20200323',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'WV', 'label': 'West Virginia', 
     'order_start_date': '20200323', 'order_relaxed_date': None, 
     'order_canceled_date': '20200504'},
    {'value': 'WI', 'label': 'Wisconsin', 'order_start_date': '20200324',
     'order_relaxed_date': None, 'order_canceled_date': None},
    {'value': 'WY', 'label': 'Wyoming', 'order_start_date': None, 
     'order_relaxed_date': None, 'order_canceled_date': None}]
